name: Bus Seat Alert

on:
  schedule:
    - cron: "*/15 * * * *"  # Runs every 15 minutes

jobs:
  check-seats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Bus Seat Checker
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: npm run check-alerts
